// 用户信息
export const SET_USER_INFO = 'USER_INFO'
export const SET_USER_AVATAR = 'SET_USER_AVATAR'
// 分类
export const GET_CATEGORY = 'GET_CATEGORY'
export const UPDATE_CATEGORY_LOADING = 'UPDATE_CATEGORY_LOADING'
export const GET_CATEGORY_TAGS = 'GET_CATEGORY_TAGS'
// 文章
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const SET_ARTICLE = 'SET_ARTICLE'
export const SET_ARTICLE_COUNT = 'SET_ARTICLE_COUNT'
